defaultSettings:
  defaultDataPath: %s
  defaultReplicaCount: %d
persistence:
  defaultClassReplicaCount: %d
  defaultFsType: xfs
service:
  ui:
    type: LoadBalancer
  manager:
    type: LoadBalancer


